services:
  audio2vtt-api:
    build: .
    container_name: audio2vtt-api
    env_file:
      - .env
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./models:/workspace/models
    restart: unless-stopped