services:
  audio2vtt-api:
    build: .
    container_name: audio2vtt-api
    env_file:
      - .env
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./models:/workspace/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=${CUDA_VISIBLE_GPUS:-all}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]